version: "3.9"
services:
  system-cloudflared:
    container_name: system-cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

  system-dashboard:
    container_name: system-dashboard
    image: lissy93/dashy
    volumes:
      - c:/Users/Saskia/repos/dh-docker/system/dashboard.yml:/app/public/conf.yml
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - UID=0
      - GID=0
    restart: unless-stopped